-- Seed data for PhotoCraft
-- Run after schema.sql

-- Insert the first course
INSERT INTO public.courses (id, title, slug, subtitle, description, long_description, price, currency, status, instructor_name, instructor_bio, meta_title, meta_description) VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Take Beautiful Photos With Your Phone',
  'phone-photography',
  'Learn to take photos you actually want to keep — using only the phone already in your pocket.',
  'A practical course that teaches you professional photography techniques adapted for smartphone cameras. No expensive equipment needed.',
  'Most smartphone photos look mediocre not because of the camera, but because of a few simple mistakes with light, lens choice, framing, and camera position. This course teaches you to see and fix these mistakes instantly. You will learn to find beautiful light anywhere, choose the right lens for every situation, compose stronger images, photograph people naturally, and edit your photos in under 60 seconds. Every lesson is short, visual, and immediately applicable. By the end, you will take noticeably better photos in every everyday situation — from family moments at home to travel and restaurants.',
  6900,
  'eur',
  'published',
  'Instructor Name',
  'Professional photographer with over 10 years of experience shooting for editorial publications, brands, and families across Europe. Passionate about helping everyday people take photos they genuinely love — without expensive cameras or complicated techniques.',
  'Take Beautiful Photos With Your Phone — Online Photography Course',
  'Learn simple professional photography techniques that immediately improve your everyday smartphone photos. No expensive camera or technical knowledge required.'
);

-- Module 1: Get Better Results Immediately
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000001-0000-0000-0000-000000000001', '11111111-1111-1111-1111-111111111111', 'Get Better Results Immediately', 'Quick changes that make an instant difference in your photos.', 0);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000001-0000-0000-0000-000000000001', 'a1000001-0000-0000-0000-000000000001', 'The Only Phone Camera Settings That Matter', 'camera-settings', 'Cut through the clutter — these are the only settings you need to change.', 'Your phone camera has dozens of settings, but only a handful actually affect your photo quality in a meaningful way. In this lesson, we focus on the three settings worth knowing: exposure lock, focus lock, and HDR. Everything else you can safely ignore for now.', 0, TRUE, 360, 'Lock your exposure and focus by tapping and holding on your subject. This single habit will improve most of your photos.', 'Open your camera app, point it at a window, then tap and hold on a person standing near the window. Notice how the exposure changes to correctly light their face instead of the bright window.'),
('b1000002-0000-0000-0000-000000000002', 'a1000001-0000-0000-0000-000000000001', 'Which Lens to Use and When', 'which-lens', 'Your phone has multiple lenses — here is when to use each one.', 'Most modern smartphones have two or three lenses: ultra-wide (0.5x), standard (1x), and telephoto (2x or 3x). Each creates a completely different look. The standard 1x lens is your workhorse. The 2x lens is ideal for portraits because it avoids facial distortion. The ultra-wide 0.5x is best for landscapes and architecture, but stretches faces badly.', 1, TRUE, 420, 'Use 2x for people, 1x for everyday shots, and 0.5x only for wide scenes where nobody is close to the camera.', 'Photograph the same person from the same distance using 0.5x, 1x, and 2x. Compare how their face looks in each photo.'),
('b1000003-0000-0000-0000-000000000003', 'a1000001-0000-0000-0000-000000000001', 'Common Mistakes That Make Photos Look Amateur', 'common-mistakes', 'These five mistakes are easy to make and easy to fix.', 'The most common smartphone photography mistakes are: shooting in bad light and hoping for the best, using digital zoom instead of walking closer, holding the camera at chest height instead of eye level, including too much cluttered background, and never editing. Each of these is simple to fix once you recognize the pattern.', 2, FALSE, 300, 'Before you press the shutter, check: Is the light good? Am I using the right lens? Is my camera at the right height? Is the background clean?', 'Take a photo the way you normally would. Then apply the checklist from this lesson and take the same photo again. Compare the two.'),
('b1000004-0000-0000-0000-000000000004', 'a1000001-0000-0000-0000-000000000001', 'Why Digital Zoom Should Usually Be Avoided', 'digital-zoom', 'Digital zoom destroys quality. Here is what to do instead.', 'Digital zoom works by cropping and enlarging the image from the sensor, which reduces resolution and introduces noise. Optical zoom (switching lenses) captures full-quality images. Whenever possible, switch to a higher lens (2x or 3x) or physically move closer to your subject rather than pinch-zooming.', 3, FALSE, 240, 'If you catch yourself pinch-zooming, stop — switch lenses or move your feet instead.', 'Take a photo of something across the room using 5x digital zoom. Then walk closer and take it at 1x or 2x. Compare the detail and sharpness.');

-- Module 2: Light
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000002-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'Light', 'Understanding light is the single biggest improvement you can make.', 1);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000005-0000-0000-0000-000000000005', 'a1000002-0000-0000-0000-000000000002', 'The Easiest Good Light Inside Your Home', 'good-light-home', 'You already have beautiful light at home — you just need to find it.', 'The best light source inside most homes is a window. Natural window light is soft, directional, and flattering. The key is positioning your subject facing the window or at a 45-degree angle to it. Avoid placing them with the window behind them unless you want a silhouette effect.', 0, FALSE, 360, 'Face your subject toward a window for instantly better indoor photos.', 'Place a family member near your largest window, facing it. Take a portrait. Then move them so the window is behind them. Compare the two results.'),
('b1000006-0000-0000-0000-000000000006', 'a1000002-0000-0000-0000-000000000002', 'Window Light', 'window-light', 'How to use window light like a professional photographer.', 'Window light creates beautiful, soft illumination that flatters faces and makes colors look natural. The size of the window and the direction matter: a large north-facing window gives even, diffused light all day. Direct sun through a window creates harder shadows — use a sheer curtain to soften it. Position your subject 1-2 meters from the window for the best results.', 1, FALSE, 420, 'A sheer curtain turns harsh direct sunlight into a beautiful, soft light source.', 'Photograph someone near a sunlit window with and without a sheer curtain. Notice how the curtain softens the shadows on their face.'),
('b1000007-0000-0000-0000-000000000007', 'a1000002-0000-0000-0000-000000000002', 'Why Ceiling Lights Often Make Photos Look Bad', 'ceiling-lights', 'Overhead light creates unflattering shadows under eyes and noses.', 'Ceiling lights cast light straight down, creating dark shadows under the eyes, nose, and chin. This makes people look tired and older. In restaurants and homes, ceiling lights are the main light source — which is why indoor photos often look unflattering. The fix is simple: turn off overhead lights and use a nearby lamp or window instead, or move your subject closer to a window.', 2, FALSE, 300, 'If a photo looks unflattering indoors, the overhead ceiling light is probably the reason. Turn it off.', 'Take a portrait under a ceiling light only. Then turn it off and use a table lamp or window instead. The difference will be dramatic.'),
('b1000008-0000-0000-0000-000000000008', 'a1000002-0000-0000-0000-000000000002', 'Backlighting', 'backlighting', 'When the light is behind your subject — and how to handle it.', 'Backlighting happens when the light source is behind your subject. Your phone camera will expose for the bright background, making your subject dark. You can fix this by tapping on your subject to lock exposure on their face, using fill flash, or repositioning so the light comes from the side. Sometimes backlighting creates a beautiful rim-light effect — learn when to embrace it and when to avoid it.', 3, FALSE, 360, 'When the background is much brighter than your subject, tap on their face to lock exposure correctly.', 'Stand someone in front of a bright window. Take a photo without adjusting. Then tap on their face to lock exposure. See the difference.'),
('b1000009-0000-0000-0000-000000000009', 'a1000002-0000-0000-0000-000000000002', 'Outdoor Light and Golden Hour', 'outdoor-light', 'The best times and conditions to photograph outdoors.', 'Outdoor light changes dramatically throughout the day. The golden hour — roughly the first and last hour of sunlight — produces warm, soft, directional light that flatters everything. Overcast days act like a giant softbox, giving you even, shadow-free light perfect for portraits. Midday sun is the most difficult: it is harsh, creates strong shadows, and makes people squint.', 4, FALSE, 480, 'The golden hour and overcast days are your best friends for outdoor photography. Avoid harsh midday sun for portraits.', 'Take the same portrait at midday and during the golden hour. Compare the warmth, softness, and shadow quality.');

-- Module 3: Composition
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000003-0000-0000-0000-000000000003', '11111111-1111-1111-1111-111111111111', 'Composition', 'How to frame your photos for maximum impact.', 2);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000010-0000-0000-0000-000000000010', 'a1000003-0000-0000-0000-000000000003', 'Where to Place the Subject', 'subject-placement', 'Centering is not always the answer — learn the rule of thirds.', 'Placing your subject slightly off-center often creates a more dynamic and interesting composition. Imagine dividing your frame into a 3x3 grid — placing important elements along these lines or at their intersections naturally draws the viewer''s eye. Most phone cameras have a grid overlay option in settings — turn it on.', 0, FALSE, 360, 'Turn on the grid overlay in your camera settings and place your subject along the lines rather than dead center.', 'Enable the grid on your camera. Take two versions of the same portrait: one centered, one with the subject on the left third line. Compare which feels more natural.'),
('b1000011-0000-0000-0000-000000000011', 'a1000003-0000-0000-0000-000000000003', 'How Much Background to Include', 'background-control', 'Less is usually more — simplify your backgrounds.', 'One of the most common composition mistakes is including too much background. A cluttered background competes with your subject for attention. Move closer, zoom in with a longer lens, or physically change your position to eliminate distracting elements. Ask yourself: does every element in the frame support the story?', 1, FALSE, 300, 'Before you shoot, look at the edges of your frame. If anything distracts from your subject, get closer or change your angle.', 'Photograph someone in a busy room. Then move closer until only the person and a clean section of wall are visible. Notice how much stronger the second photo feels.'),
('b1000012-0000-0000-0000-000000000012', 'a1000003-0000-0000-0000-000000000003', 'Camera Height Changes Everything', 'camera-height', 'The height you hold your phone at dramatically affects the look of a photo.', 'Most people photograph from chest or standing height, which creates a slightly downward angle. For portraits, hold the camera at the subject''s eye level. For children, kneel down. Shooting slightly below eye level can feel powerful and heroic. Shooting from above looks down on the subject. Camera height is one of the simplest and most overlooked ways to improve a photo.', 2, FALSE, 360, 'Always match your camera height to your subject''s eye level. For children, that means kneeling down.', 'Photograph a child from standing height, then kneel and photograph from their eye level. The eye-level photo will feel dramatically more engaging.'),
('b1000013-0000-0000-0000-000000000013', 'a1000003-0000-0000-0000-000000000003', 'Creating Depth', 'creating-depth', 'Make flat phone photos feel three-dimensional.', 'Phone photos can feel flat because the small sensor struggles with depth separation. You can create the illusion of depth by including foreground elements, using leading lines, choosing a longer lens (2x or 3x), positioning your subject away from the background, and shooting through objects like doorways or foliage.', 3, FALSE, 360, 'Include something in the foreground and separate your subject from the background to create the illusion of depth.', 'Find a pathway, hallway, or row of trees. Photograph someone walking along it, using the lines to create depth. Compare with a flat, straight-on photo.');

-- Module 4: Photographing People
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000004-0000-0000-0000-000000000004', '11111111-1111-1111-1111-111111111111', 'Photographing People', 'Practical techniques for better portraits and candid moments.', 3);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000014-0000-0000-0000-000000000014', 'a1000004-0000-0000-0000-000000000004', 'Better Portraits With Your Phone', 'better-portraits', 'Simple techniques that make smartphone portraits look professional.', 'Great portraits come from good light, the right lens, and the right camera height — not from an expensive camera. Use the 2x lens to avoid facial distortion. Place your subject facing a window or in open shade. Hold the camera at their eye level. Keep the background simple. These four adjustments alone will make your portraits dramatically better.', 0, FALSE, 420, 'The portrait formula: 2x lens + window light + eye level + simple background.', 'Use the portrait formula on a family member. Then try breaking each rule one at a time to see the effect.'),
('b1000015-0000-0000-0000-000000000015', 'a1000004-0000-0000-0000-000000000004', 'Natural Poses and Expressions', 'natural-poses', 'How to help people look relaxed and natural in photos.', 'Most people freeze when a camera appears. Help them relax by giving simple actions rather than poses: walk toward me, look at each other, pick up the child, lean against the wall. Movement creates natural body language. Shoot continuously during the action rather than waiting for a perfect still moment. Talk to your subject — the best expressions come from real interaction, not "say cheese."', 1, FALSE, 360, 'Give your subject something to do. Action creates natural poses and genuine expressions.', 'Instead of saying "smile," ask your subject to walk toward you while looking down, then look up. Capture the moment they look up — it will feel natural.'),
('b1000016-0000-0000-0000-000000000016', 'a1000004-0000-0000-0000-000000000004', 'Photographing Children', 'photographing-children', 'Children move fast — here is how to capture them beautifully.', 'Children rarely sit still, and that is actually an advantage. The best children''s photos capture movement and genuine emotion. Get down to their eye level. Use burst mode to capture multiple frames. Let them play and photograph the in-between moments. Use the 1x or 2x lens so you can stay close enough to capture expressions without crowding them.', 2, FALSE, 420, 'The secret to photographing children: get low, stay close, shoot continuously, and let them be themselves.', 'Let a child play freely near a window. Kneel to their level and use burst mode to capture a sequence. Choose the frame with the best expression.'),
('b1000017-0000-0000-0000-000000000017', 'a1000004-0000-0000-0000-000000000004', 'Avoiding Distorted Faces', 'avoiding-distortion', 'Why some phone photos make faces look strange — and how to prevent it.', 'Wide-angle lenses (especially 0.5x) distort facial features when used close up, making noses larger and faces wider. The 1x lens is acceptable at a moderate distance, but the 2x or 3x lens produces the most flattering facial proportions. Never take a close-up portrait with the ultra-wide lens. If you must use 1x, keep at least an arm''s length of distance.', 3, FALSE, 240, 'For flattering faces, always use 2x or 3x. Never photograph faces close-up with the ultra-wide lens.', 'Take a selfie with 0.5x, 1x, and 2x (using the timer). Compare how your face shape changes. The difference is striking.');

-- Module 5: Everyday Situations
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000005-0000-0000-0000-000000000005', '11111111-1111-1111-1111-111111111111', 'Everyday Situations', 'How to take great photos in specific common scenarios.', 4);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000018-0000-0000-0000-000000000018', 'a1000005-0000-0000-0000-000000000005', 'Indoor Family Moments', 'indoor-family', 'Better photos of everyday life at home.', 'The key to great indoor family photos is window light and the right moment. Move your family activities near the biggest window in your home. Turn off overhead lights. Use the 1x or 2x lens. Photograph during activities — reading, cooking, playing — rather than posed smiles. Indoor family photos are about documenting real life in beautiful light.', 0, FALSE, 360, 'Move activities near windows, turn off overhead lights, and photograph during real moments rather than posed ones.', 'During your next family meal, seat everyone near a window. Photograph the natural interactions without asking anyone to look at the camera.'),
('b1000019-0000-0000-0000-000000000019', 'a1000005-0000-0000-0000-000000000005', 'Restaurants and Cafés', 'restaurants', 'How to take beautiful photos when eating out.', 'Restaurant lighting is typically the enemy of good photos: overhead downlights and dim ambience. Sit near windows whenever possible. Photograph food from above (the overhead angle works well for flat dishes) or at 45 degrees for dishes with height. Use the 1x lens for table shots. If the restaurant is dark, increase exposure by tapping and swiping up on your screen.', 1, FALSE, 300, 'In restaurants, choose a window table. Shoot food from above or at 45 degrees. Increase exposure in dim settings.', 'At your next restaurant visit, take one photo under the table lamp and one near the window. The window-light version will look significantly better.'),
('b1000020-0000-0000-0000-000000000020', 'a1000005-0000-0000-0000-000000000005', 'Travel Photography', 'travel', 'Capture your trips with photos worth sharing.', 'Great travel photography tells a story. Include people for scale and emotion. Photograph during the golden hour when the light is warmest. Look for interesting foreground elements to add depth. Photograph details — textures, signs, food — not just landmarks. Use the 0.5x lens for grand landscapes and architecture, but switch to 1x or 2x for street scenes and people.', 2, FALSE, 480, 'Great travel photos include people, interesting light, details, and depth — not just landmarks from the standard tourist angle.', 'At a landmark, take the standard tourist shot. Then find a different angle, wait for interesting light, or include a person in the frame. Compare the results.'),
('b1000021-0000-0000-0000-000000000021', 'a1000005-0000-0000-0000-000000000005', 'Food Photography', 'food-photography', 'Make your meals look as good in photos as they do on the plate.', 'Food looks best in natural light, shot from directly above or at a 45-degree angle. Arrange the plate so the most interesting element faces the camera. Remove clutter from the table. Use the 1x lens for overhead shots and 2x for close-up detail. A dark, simple background makes colorful food pop. Avoid flash — it makes food look flat and unappetizing.', 3, FALSE, 300, 'Natural light from the side, shoot from above, clean the frame, and never use flash.', 'Photograph your next meal: first under ceiling light with flash, then near a window without flash, shot from above. The second version will look restaurant-worthy.');

-- Module 6: Editing
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000006-0000-0000-0000-000000000006', '11111111-1111-1111-1111-111111111111', 'Editing', 'Simple edits that make your photos look polished.', 5);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000022-0000-0000-0000-000000000022', 'a1000006-0000-0000-0000-000000000006', 'Exposure, Contrast, and Color', 'exposure-contrast', 'The three editing adjustments that matter most.', 'Every photo editing app has dozens of sliders, but three adjustments handle 80% of the improvement: brightness (exposure), contrast, and color temperature (white balance). Increase exposure slightly for a clean, airy look. Add a touch of contrast for definition. Adjust white balance to remove unwanted color casts — cooler for overly yellow indoor shots, warmer for cold outdoor ones.', 0, FALSE, 360, 'Start every edit with three adjustments: exposure, contrast, and white balance. These three alone will transform most photos.', 'Open a recent indoor photo. Increase brightness slightly, add a small amount of contrast, and adjust white balance until skin tones look natural. Compare before and after.'),
('b1000023-0000-0000-0000-000000000023', 'a1000006-0000-0000-0000-000000000006', 'Highlights, Shadows, and Cropping', 'highlights-shadows', 'Recover detail and tighten your composition after the shot.', 'Reducing highlights recovers detail in bright areas (windows, skies). Lifting shadows reveals detail in dark areas (faces in shade). These two adjustments together dramatically improve dynamic range. Cropping lets you fix composition mistakes after the fact: remove distracting edges, straighten horizons, and tighten the frame around your subject.', 1, FALSE, 360, 'Pull down highlights, push up shadows, then crop to strengthen the composition. These tools fix most exposure problems.', 'Find a photo where the sky is blown out. Reduce highlights and the sky detail should reappear. Lift shadows if faces are too dark.'),
('b1000024-0000-0000-0000-000000000024', 'a1000006-0000-0000-0000-000000000006', 'A Fast 60-Second Editing Workflow', 'fast-editing', 'A complete editing routine you can do in under a minute.', 'Here is a professional-speed workflow: 1) Straighten and crop for better composition. 2) Adjust exposure. 3) Pull highlights down, lift shadows up. 4) Add a touch of contrast. 5) Correct white balance. 6) Increase saturation or vibrance slightly if needed. Done. Six steps, under 60 seconds. With practice, this becomes automatic. Every photo you take can benefit from this quick pass.', 2, TRUE, 300, 'Six steps, sixty seconds: straighten, exposure, highlights/shadows, contrast, white balance, saturation. Make this your editing habit.', 'Set a timer for 60 seconds. Edit a photo following the six-step workflow. Do this for five photos in a row to build the habit.');

-- Module 7: Before and After
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000007-0000-0000-0000-000000000007', '11111111-1111-1111-1111-111111111111', 'Before and After', 'Real examples where one or two changes create a dramatic improvement.', 6);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000025-0000-0000-0000-000000000025', 'a1000007-0000-0000-0000-000000000007', 'Lens Choice Comparison', 'lens-comparison', 'See how choosing the right lens transforms a portrait.', 'In this example, we photograph the same person from the same position using 0.5x, 1x, and 2x. The ultra-wide version stretches and distorts the face. The 1x version is acceptable. The 2x version looks like it was taken with a professional camera. One simple change — switching lenses — completely transforms the portrait.', 0, FALSE, 300, 'The right lens can make the difference between an amateur snapshot and a professional-looking portrait.', NULL),
('b1000026-0000-0000-0000-000000000026', 'a1000007-0000-0000-0000-000000000007', 'Light Position Change', 'light-comparison', 'Moving one meter can completely change the quality of light on your subject.', 'Here we photograph the same person in two positions: facing away from the window (backlit, dark face) and facing toward the window (beautifully lit). The only change was rotating 180 degrees. No editing, no special technique — just understanding where the light is coming from.', 1, FALSE, 300, 'Always notice where the light is coming from. Move your subject so the light falls on their face, not their back.', NULL),
('b1000027-0000-0000-0000-000000000027', 'a1000007-0000-0000-0000-000000000007', 'Camera Height and Background', 'height-background', 'Two simple physical adjustments that elevate a photo.', 'In this comparison, the first photo is taken from standing height with a messy background. The second photo is taken from the subject''s eye level with a cleaner background achieved by moving two steps to the right. Same phone, same subject, same moment — dramatically different result.', 2, FALSE, 300, 'Change your height and check your background. These two physical adjustments cost nothing and improve almost every photo.', NULL);

-- Module 8: Practical Challenges
INSERT INTO public.modules (id, course_id, title, description, order_index) VALUES
('a1000008-0000-0000-0000-000000000008', '11111111-1111-1111-1111-111111111111', 'Practical Challenges', 'Put your new skills to work with hands-on assignments.', 7);

INSERT INTO public.lessons (id, module_id, title, slug, description, content, order_index, is_preview, video_duration, key_takeaway, practical_example) VALUES
('b1000028-0000-0000-0000-000000000028', 'a1000008-0000-0000-0000-000000000008', 'Window Light Portrait Challenge', 'challenge-window-light', 'Photograph someone using only window light.', 'Your challenge: Find the best window in your home. Place someone facing it at a 45-degree angle. Use the 2x lens at eye level. Take the best portrait you can. Then try variations: change the angle, distance from the window, and whether or not you use a curtain. Keep the version you are happiest with.', 0, FALSE, 180, 'Practice using window light deliberately. This single skill improves all your indoor photography.', NULL),
('b1000029-0000-0000-0000-000000000029', 'a1000008-0000-0000-0000-000000000008', 'Lens Comparison Challenge', 'challenge-lens', 'Take the same portrait with three different lenses.', 'Photograph the same person at 0.5x, 1x, and 2x from the same position. Then try again from different distances. Notice how each lens changes the look and feel of the portrait. Which lens produces the most flattering result for faces?', 1, FALSE, 180, 'Understanding your lenses is one of the most practical skills you can develop.', NULL),
('b1000030-0000-0000-0000-000000000030', 'a1000008-0000-0000-0000-000000000008', '60-Second Edit Challenge', 'challenge-editing', 'Edit five photos in under five minutes.', 'Select five recent photos from your camera roll. Set a timer for one minute per photo. Apply the six-step editing workflow from the editing module: straighten, exposure, highlights/shadows, contrast, white balance, saturation. The goal is to build speed and make the workflow automatic.', 2, FALSE, 180, 'Speed editing is a skill that improves with practice. Five photos, five minutes — make it a weekly habit.', NULL);

-- Insert sample assignments (future-ready)
INSERT INTO public.assignments (lesson_id, title, instructions, order_index) VALUES
('b1000005-0000-0000-0000-000000000005', 'Window Light Portrait', 'Photograph someone using only window light. Position them facing the window or at a 45-degree angle. Share your best result.', 0),
('b1000002-0000-0000-0000-000000000002', 'Lens Comparison', 'Take the same portrait using 0.5x, 1x, and 2x lenses. Share all three photos.', 0),
('b1000011-0000-0000-0000-000000000011', 'Clean Background', 'Take a portrait with a cluttered background. Then find a cleaner angle and retake. Share both versions.', 0),
('b1000016-0000-0000-0000-000000000016', 'Moving Child', 'Photograph a child playing using burst mode at their eye level. Share your three favorite frames.', 0),
('b1000024-0000-0000-0000-000000000024', '60-Second Edit', 'Edit a photo using the six-step workflow in under 60 seconds. Share the before and after.', 0);
